[project]
name = "image-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dependency-injector>=4.49.0",
    "fastapi[standard]>=0.136.3",
    "numpy>=2.4.6",
    "pymongo>=4.17.0",
    "uvicorn[standard]>=0.48.0",
]

[dependency-groups]
dev = ["pytest>=9.0.1", "pytest-cov>=7.0.0", "ruff>=0.14.7"]
