name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'services/monolith/**'
      - '.github/workflows/monolith-ci.yml'
      - '.github/actions/python/**'
  pull_request:
    paths:
      - 'services/monolith/**'
      - '.github/workflows/monolith-ci.yml'
      - '.github/actions/python/**'

permissions:
  pull-requests: write

env:
  DIRECTORY: services/monolith

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup backend
        uses: ./.github/actions/python/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run ruff format
        run: cd ${{ env.DIRECTORY }} && uv run ruff format --diff

  check:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        
      - name: Setup backend
        uses: ./.github/actions/python/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run ruff check
        run: cd ${{ env.DIRECTORY }} && uv run ruff check --output-format github
      # - name: Run pyright
      #   run: uv run pyright


  tests:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup service
        uses: ./.github/actions/python/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run unit tests
        uses: ./.github/actions/python/pytest
        with:
          directory: ${{ env.DIRECTORY }}
          test_type: unit

      - name: Run integration tests
        uses: ./.github/actions/python/pytest
        with:
          directory: ${{ env.DIRECTORY }}
          test_type: integration

      - name: Report coverage to OctoCov
        uses: k1LoW/octocov-action@v1
        with:
          work-dir: ${{ env.DIRECTORY }}
        continue-on-error: true
  